insert into BankRegistry (id, bankId, bankName) values (1, 1010, 'Narodowy Bank Polski');
insert into BankRegistry (id, bankId, bankName) values (2, 1020, 'PKO BP');
insert into BankRegistry (id, bankId, bankName) values (3, 1030, 'Citybank');
insert into BankRegistry (id, bankId, bankName) values (4, 1050, 'ING');
insert into BankRegistry (id, bankId, bankName) values (5, 1060, 'BPH');
insert into BankRegistry (id, bankId, bankName) values (6, 1090, 'BZ WBK');
insert into BankRegistry (id, bankId, bankName) values (7, 11400000, 'BRE Bank');
insert into BankRegistry (id, bankId, bankName) values (8, 11402004, 'mBank');
insert into BankRegistry (id, bankId, bankName) values (9, 11402017, 'Multibank');
insert into BankRegistry (id, bankId, bankName) values (10, 1160, 'Bank Millennium');
insert into BankRegistry (id, bankId, bankName) values (11, 1240, 'PKO');
insert into BankRegistry (id, bankId, bankName) values (12, 1280, 'HSBC');
insert into BankRegistry (id, bankId, bankName) values (13, 1300, 'Meritum Bank');
insert into BankRegistry (id, bankId, bankName) values (14, 1320, 'Bank Pocztowy');
insert into BankRegistry (id, bankId, bankName) values (15, 1440, 'Nordea Bank');
insert into BankRegistry (id, bankId, bankName) values (16, 1470, 'Euro Bank');
insert into BankRegistry (id, bankId, bankName) values (17, 1540, 'BOŚ');
insert into BankRegistry (id, bankId, bankName) values (18, 1600, 'BNP Paribas Fortis');
insert into BankRegistry (id, bankId, bankName) values (19, 1680, 'Invest Bank');
insert into BankRegistry (id, bankId, bankName) values (20, 1740, 'DZ Bank');
insert into BankRegistry (id, bankId, bankName) values (21, 1750, 'Raiffeisen Bank');
insert into BankRegistry (id, bankId, bankName) values (22, 1870, 'Polski Bank Przedsiębiorczości');
insert into BankRegistry (id, bankId, bankName) values (23, 1880, 'Deutsche Bank Polska');
insert into BankRegistry (id, bankId, bankName) values (24, 1910, 'Deutsche Bank PBC');
insert into BankRegistry (id, bankId, bankName) values (25, 1940, 'Credit Agricole Bank Polska');
insert into BankRegistry (id, bankId, bankName) values (26, 1950, 'Idea Bank');
insert into BankRegistry (id, bankId, bankName) values (27, 2030, 'BGŻ');
insert into BankRegistry (id, bankId, bankName) values (28, 2120, 'Santander Consumer Bank');
insert into BankRegistry (id, bankId, bankName) values (29, 2130, 'Volkswagen Bank');
insert into BankRegistry (id, bankId, bankName) values (30, 2160, 'Toyota Bank');
insert into BankRegistry (id, bankId, bankName) values (31, 2190, 'DnB Nord');
insert into BankRegistry (id, bankId, bankName) values (32, 2480, 'Getin Noble Bank');
insert into BankRegistry (id, bankId, bankName) values (33, 2490, 'Alior Bank');
insert into BankRegistry (id, bankId, bankName) values (34, 2530, 'FM Bank');